spring.application.name=${SPRING_APPLICATION_NAME:StudentGrader}

# ===============================
# DATABASE CONFIGURATION (Railway MySQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

# ===============================
# MAIL CONFIGURATION (GMAIL)
# ===============================

sendgrid.api.key=${SENDGRID_API_KEY:test}

sendgrid.from.email=bhiseamarwagholi@gmail.com
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=bhiseamarwagholi@gmail.com
#spring.mail.password=wpul bxsw bgcu raeo

#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.enable=true

#spring.mail.properties.mail.smtp.connectiontimeout=10000
#spring.mail.properties.mail.smtp.timeout=10000
#spring.mail.properties.mail.smtp.writetimeout=10000